/******************************************************************************
 *  
 *  Purpose:  Minimum number of notes and the notes to be generated by Vending machine
 *  @author  Swetalina
 *  @version 1.0
 *  @since   22-05-2018
 *
 ******************************************************************************/
package com.bridgelabz.algorithms;

import com.bridgelabz.utility.Utility;

public class VendingMachine {

	public static void main(String[] args) {
		Utility utility = new Utility();
		System.out.println("Enter an amount");
		int amount = utility.readInteger();
		utility.generateChange(amount);

	}

}
